use pañalera;

insert into Localidades (fk_Provincia,nombre,baja) Values (2,'ALVEAR',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'BELLA VISTA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'CORRIENTES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'CURUZÚ CUATIÁ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'ESQUINA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'VIRASORO ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'GOYA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'MERCEDES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'MONTE CASEROS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'PASO DE LOS LIBRES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'SALADAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'SANTO TOMÉ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'BERÓN DE ASTRADA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'CAÁ CATÍ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'COLONIA SANTA ROSA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'CONCEPCIÓN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'EMPEDRADO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'ITATÍ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'ITUZAINGÓ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'LA CRUZ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'MBURUCUYÁ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'MOCORETÁ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'PASO DE LA PATRIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'SAN COSME',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'SAN LUÍS DEL PALMAR',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'SAN MIGUEL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'SAN ROQUE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'SANTA LUCÍA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (2,'SAUCE',0);
