use sistema;
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'AVIA TERAI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'BARRANQUERAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'BASAIL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'CAMPO LARGO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'CAPITAN  SOLARI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'CHARADAI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'CHARATA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'CHOROTIS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'COLONIA BENITEZ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'COLONIA ELISA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'COLONIA POPULAR',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'COLONIAS UNIDAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'COMANDANCIA FRIAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'CONCEPCION DEL BERMEJO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'CORONEL DU GRATY',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'CORZUELA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'COTE LAI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'EL ESPINILLO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'EL SAUZALITO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'EL TACURUZAL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'EL TARTAGAL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'ENRIQUE URIEN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'FONTANA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'FORTIN LAVALLE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'FUERTE ESPERANZA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'GANCEDO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'GENERAL CAPDEVILA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'GENERAL PINEDO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'GENERAL SAN MARTIN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'GENERAL VEDIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'HAUMONIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'HERMOSO CAMPO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'HORQUILLA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'ISLA DEL CERRITO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'ITIN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'JUAN JOSE CASTELLI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'LA CLOTILDE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'LA EDUVIGIS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'LA ESCONDIDA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'LA LEONESA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'LA TIGRA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'LA VERDE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'LAGUNA BLANCA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'LAGUNA LIMPIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'LAPACHITO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'LAS BREÑAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'LAS GARCITAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'LAS HACHERAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'LAS PALMAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'LOS FRENTONES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'MACHAGAI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'MAKALLE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'MARGARITA BELEN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'MIRAFLORES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'MISION NVA. POMPEYA ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'NAPALPI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'NAPENAY',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'PAMPA ALMIRON',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'PAMPA DEL INDIO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'PAMPA DEL INFIERNO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'PRESIDENCIA DE LA PLAZA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'PRESIDENCIA ROCA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'PTE. CHACO - CORRIENTES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'PUERTO BERMEJO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'PUERTO TIROL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'PUERTO VELAZ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'PUERTO VILELAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'QUITILIPI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'RESISTENCIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'RIO MUERTO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'SAENZ PEÑA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'SAMUHU',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'SAN BERNARDO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'SANTA SYLVINA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'SELVAS DEL RIO DE ORO ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'TACO POZO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'TRES ISLETAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'VILLA ANGELA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'VILLA BERTHET',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'VILLA RIO BERMEJITO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'WICHI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (1, 'ZUBERBUHLER',0);

