use pañalera;

insert into Localidades (fk_Provincia,nombre,baja) Values (3,'FORMOSA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'INGENIERO JUÁREZ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'COMANDANTE FONTANA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'MISIÓN SAN FRANCISCO DE LAISHI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'RIACHO HE-HÉ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'SAN MARTÍN II',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'EL POTRILLO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'TRES LAGUNAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'SUBTENIENTE PERÍN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'BUENA VISTA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'CLORINDA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'LAS LOMITAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'PALO SANTO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'ESTANISLAO DEL CAMPO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'EL ESPINILLO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'GENERAL LUCIO V. MANSILLA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'MISIÓN TACAAGLÉ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'FORTÍN LUGONES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'MOJÓN DE FIERRO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'SIETE PALMAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'PIRANÉ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'IBARRETA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'VILLA GENERAL GÜEMES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'POZO DEL TIGRE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'GENERAL MANUEL BELGRANO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'HERRADURA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'LAGUNA NAINECK',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'VILLA ESCOLAR',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'COLONIA PASTORIL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'POZO DE MAZA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'EL COLORADO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'LAGUNA BLANCA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'VILLA DOS TRECE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'MAYOR VICENTE VILLAFAÑE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'LAGUNA YEMA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'VILLA DEL CARMEN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'GENERAL MOSCONI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'LOS CHIRIGUANOS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'GRAN GUARDIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (3,'RIACHO NEGRO',0);
