use pañalera;

insert into Localidades (fk_Provincia,nombre,baja) Values (5,'AARÓN CASTELLANOS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ACEBAL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'AGUARÁ GRANDE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ALBARELLOS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ALCORTA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ALDAO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ALDAO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ALEJANDRA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ÁLVAREZ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ALVEAR',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'AMBROSETTI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'AMENÁBAR',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ÁNGEL GALLARDO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ANGÉLICA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ANGELONI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ARBILLA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'AREQUITO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ARMINDA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ARMSTRONG',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'AROCENA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ARROYO AGUIAR',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ARROYO CEIBAL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ARROYO LEYES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ARROYO SECO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ARRUFÓ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ARTEAGA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ATALIVA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'AURELIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'AVELLANEDA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'BALNEARIO LA VERDE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'BALNEARIO MONJE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'BARRANCAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'BARRIO ARROYO DEL MEDIO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'BARRIO CAIMA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'BARRIO CICARELLI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'BARRIO EL PACAÁ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'BARRIO MITRE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'BARRIOS ACAPULCO Y VERACRUZ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'BAUER Y SIGEL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'BELLA ITALIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'BERABEVÚ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'BERNA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'BERNARDO DE IRIGOYEN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'BIGAND',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'BOMBAL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'BOUQUET',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'BUSTINZA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CABAL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CACIQUE ARIACAIQUÍN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CAFFERATA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CALCHAQUÍ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CAMPO ANDINO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CAÑADA DE GÓMEZ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CAÑADA DEL UCLE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CAÑADA OMBÚ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CAÑADA RICA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CAÑADA ROSQUÍN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CANDIOTI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CAPITÁN BERMÚDEZ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CAPIVARA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CARCARAÑÁ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CARLOS PELLEGRINI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CARMEN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CARMEN DEL SAUCE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CARRERAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CARRIZALES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CASALEGNO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CASAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CASILDA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CASTELAR',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CASTELLANOS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CAVOUR',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CAYASTÁ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CAYASTACITO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CENTENO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CEPEDA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CERES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CHABÁS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CHAÑAR LADEADO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CHAPUY',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CHOVET',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CHRISTOPHERSEN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CLASSON',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'COLMENA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'COLONIA ANA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'COLONIA BELGRANO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'COLONIA BICHA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'COLONIA BOSSI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'COLONIA CELLO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'COLONIA DOLORES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'COLONIA DURÁN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'COLONIA MARGARITA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'COLONIA MÉDICI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'COLONIA RAQUEL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'COLONIA ROSA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CONSTANZA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CORONDA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CORONEL ARNOLD',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CORONEL BOGADO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CORONEL FRAGA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CORONEL RODOLFO S. DOMÍNGUEZ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CORREA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CRISPI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CUATRO ESQUINAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CULULÚ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'CURUPAYTÍ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'DESVÍO ARIJÓN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'DÍAZ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'DIEGO DE ALVEAR',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'EGUSQUIZA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'EL ARAZÁ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'EL CARAMELO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ELISA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ELORTONDO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'EL RABÓN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'EL TRÉBOL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'EMILIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'EMPALME SAN CARLOS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'EMPALME VILLA CONSTITUCIÓN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ESMERALDA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ESPERANZA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ESTACIÓN CLUCELLAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ESTACIÓN SAGUIER',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ESTEBAN RAMS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ESTHER',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'EUSEBIA Y CAROLINA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'EUSTOLIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'FELICIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'FIGHIERA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'FIRMAT',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'FIRMAT',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'FLORENCIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'FORTÍN OLMOS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'FRANCK',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'FRAY LUIS BELTRÁN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'FRONTERA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'FUENTES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'FUNES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'GABOTO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'GÁLVEZ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'GARABATO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'GARIBALDI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'GATO COLORADO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'GENERAL GELLY',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'GENERAL LAGOS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'GESSLER',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'GOBERNADOR CRESPO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'GÖDEKEN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'GODOY',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'GOLONDRINA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'GRANADERO BAIGORRIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'GREGORIA PÉREZ DE DENIS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'GRUTLY',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'GUADALUPE NORTE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'HELVECIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'HERSILIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'HIPATIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'HUANQUEROS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'HUGHES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'HUMBERTO PRIMO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'HUMBOLDT',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'IBARLUCEA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'IBARLUCEA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'INGENIERO CHANOURDIE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'INTIYACO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'IRIGOYEN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'JACINTO L. ARÁUZ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'JOSEFINA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'JUAN BERNABÉ MOLINA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'JUNCAL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'KILÓMETRO 101',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'KILÓMETRO 115',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LABORDEBOY',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LA BRAVA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LA CABRAL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LA CHISPA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LA CRIOLLA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LA GALLARETA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LAGUNA PAIVA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LA ISLETA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LA LUCILA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LANDETA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LANTERI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LA PELADA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LA PENCA Y CARAGUATÁ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LARGUÍA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LARRECHEA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LA RUBIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LA SARITA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LAS AVISPAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LAS BANDURRIAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LAS GARZAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LAS PALMERAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LAS PAREJAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LAS PETACAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LAS ROSAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LAS TOSCAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LAS TUNAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LA VANGUARDIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LAZZARINO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LEHMANN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LLAMBI CAMPBELL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LOGROÑO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LOMA ALTA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LÓPEZ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LOS AMORES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LOS CARDOS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LOS LAURELES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LOS MOLINOS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LOS MUCHACHOS - LA ALBORADA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LOS NOGALES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LOS QUIRQUINCHOS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LOS ZAPALLOS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LUCIO V. LÓPEZ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'LUIS PALACIOS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'MACIEL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'MAGGIOLO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'MALABRIGO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'MARCELINO ESCALADA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'MARGARITA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'MARÍA JUANA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'MARÍA LUISA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'MARÍA SUSANA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'MARÍA TERESA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'MATILDE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'MÁXIMO PAZ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'MELINCUÉ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'MIGUEL TORRES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'MOISÉS VILLE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'MONIGOTES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'MONJE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'MONTEFIORE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'MONTE FLORES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'MONTES DE OCA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'MONTE VERA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'MURPHY',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ÑANDUCITA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'NARÉ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'NELSON',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'NUEVA LEHMANN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'NUEVO TORINO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'OLIVEROS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PALACIOS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PARAJE 29',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PARAJE CHACO CHICO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PARAJE LA COSTA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PARAJE SAN MANUEL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PAVÓN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PAVÓN ARRIBA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PEDRO GÓMEZ CELLO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PÉREZ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PEYRANO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PIAMONTE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PILAR',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PIÑERO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PLAZA CLUCELLAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PLAZA MATILDE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PLAZA SAGUIER',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'POZO BORRADO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'POZO DE LOS INDIOS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PRESIDENTE ROCA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PROGRESO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PROVIDENCIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PUEBLO ANDINO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PUEBLO ESTHER',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PUEBLO MARINI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PUEBLO MUÑOZ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PUEBLO SANTA LUCÍA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PUEBLO URANGA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PUERTO ARAGÓN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PUERTO ARROYO SECO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PUERTO GENERAL SAN MARTÍN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PUERTO RECONQUISTA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'PUJATO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'RAFAELA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'RAMAYÓN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'RAMONA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'RECONQUISTA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'RECREO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'RICARDONE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'RINCÓN POTRERO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ROLDÁN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ROMANG',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ROSARIO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'RUEDA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'RUFINO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SALADERO MARIANO CABAL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SALTO GRANDE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN AGUSTÍN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN ANTONIO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN ANTONIO DE OBLIGADO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN BERNARDO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN BERNARDO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN CARLOS CENTRO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN CARLOS NORTE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN CARLOS SUD',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN CRISTÓBAL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SANCTI SPIRITU',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN EDUARDO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN EUGENIO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN FABIÁN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SANFORD',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN FRANCISCO DE SANTA FE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN GENARO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN GENARO NORTE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN GREGORIO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN GUILLERMO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN JAVIER',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN JERÓNIMO DEL SAUCE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN JERÓNIMO NORTE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN JERÓNIMO SUD',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN JORGE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN JOSÉ DE LA ESQUINA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN JOSÉ DEL RINCÓN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN JUSTO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN LORENZO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN MARIANO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN MARTÍN DE LAS ESCOBAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN MARTÍN NORTE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SANTA CLARA DE BUENA VISTA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SANTA CLARA DE SAGUIER',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SANTA FE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SANTA ISABEL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SANTA MARGARITA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SANTA ROSA DE CALCHINES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SANTA TERESA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SANTO DOMINGO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SANTO TOMÉ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SANTURCE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAN VICENTE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SA PEREIRA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SARGENTO CABRAL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SARMIENTO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SASTRE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SAUCE VIEJO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SERODINO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SILVA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SOLDINI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SOLEDAD',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'STEPHENSON',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SUARDI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SUNCHALES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'SUSANA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'TACUARENDÍ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'TACURAL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'TARTAGAL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'TEODELINA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'THEOBALD',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'TIMBÚES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'TOBA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'TORTUGAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'TOSTADO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'TOTORAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'TRAILL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'VENADO TUERTO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'VERA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'VERA Y PINTADO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'VIDELA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'VILA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'VILLA AMELIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'VILLA ANA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'VILLA CAÑÁS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'VILLA CONSTITUCIÓN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'VILLADA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'VILLA DEL PLATA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'VILLA ELOÍSA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'VILLA ELVIRA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'VILLA GOBERNADOR GÁLVEZ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'VILLA GUILLERMINA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'VILLA JOSEFINA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'VILLA LA RIVERA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'VILLA LAURA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'VILLA MINETTI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'VILLA MUGUETA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'VILLA OCAMPO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'VILLA SAN JOSÉ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'VILLA SARALEGUI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'VILLA TRINIDAD',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'VIRGINIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'WHEELWRIGHT',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'WILDERMUTH',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ZAVALLA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (5,'ZENÓN PEREYRA',0);
