use pañalera;

insert into Localidades (fk_Provincia,nombre,baja) Values (4,'1º DE MAYO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'25 DE MAYO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'9 DE JULIO KILÓMETRO 20',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'9 DE JULIO KILÓMETRO 28',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'ALBA POSSE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'ALICIA ALTA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'ALICIA BAJA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'ALMAFUERTE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'APÓSTOLES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'ARISTÓBULO DEL VALLE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'ARROYO DEL MEDIO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'AZARA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'BARRA CONCEPCIÓN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'BARRIO CUATRO BOCAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'BARRIO DEL LAGO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'BARRIO ESCUELA 461',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'BARRIO ESCUELA 633',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'BARRIO GUATAMBÚ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'BARRIO ITÁ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'BARRIO NUEVO GARUPA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'BARRIO RURAL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'BARRIO TUNGOIL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'BERNARDO DE IRIGOYEN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'BONPLAND',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'CAÁ - YARÍ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'CABUREI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'CAMPO GRANDE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'CAMPO RAMÓN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'CAMPO VIERA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'CANDELARIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'CAPIOVÍ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'CARAGUATAY',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'CERRO AZUL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'CERRO CORÁ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'COLONIA ALBERDI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'COLONIA AURORA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'COLONIA POLANA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'COLONIA VICTORIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'COLONIA WANDA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'COMANDANTE ANDRESITO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'CONCEPCIÓN DE LA SIERRA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'COPIOVICIÑO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'CORPUS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'CRUCE CABALLERO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'DOMINGO SAVIO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'DOS ARROYOS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'DOS DE MAYO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'DOS DE MAYO NÚCLEO III',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'DOS HERMANAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'EL ALCÁZAR',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'ELDORADO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'EL SALTO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'EL SOBERBIO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'ESTACIÓN APÓSTOLES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'FLORENTINO AMEGHINO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'FRACRÁN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'GARUHAPÉ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'GARUPÁ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'GENERAL ALVEAR',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'GENERAL URQUIZA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'GOBERNADOR LÓPEZ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'GOBERNADOR ROCA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'GUARANÍ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'HELVECIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'HIPÓLITO YRIGOYEN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'INTEGRACIÓN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'ITACARUARÉ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'JARDÍN AMÉRICA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'KILÓMETRO 17',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'LA CORITA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'LAHARRAGUE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'LEANDRO N. ALEM',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'LORETO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'LOS HELECHOS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'MARÍA MAGDALENA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'MÁRTIRES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'MBOPICUÁ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'MOJÓN GRANDE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'MONTECARLO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'NEMESIO PARMA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'NUEVA DELICIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'OASIS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'OBERÁ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'OLEGARIO V. ANDRADE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'PANAMBÍ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'PANAMBÍ KILÓMETRO 15',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'PANAMBÍ KILÓMETRO 8',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'PARAÍSO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'PIÑALITO NORTE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'PIÑALITO SUR',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'PINDAPOY',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'PIRAY KILÓMETRO 18',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'POSADAS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'PROFUNDIDAD',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'PUEBLO ILLIA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'PUEBLO NUEVO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'PUERTO ANDRESITO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'PUERTO DESEADO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'PUERTO ESPERANZA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'PUERTO IGUAZÚ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'PUERTO LEONI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'PUERTO LIBERTAD',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'PUERTO MADO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'PUERTO PINARES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'PUERTO PIRAY',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'PUERTO RICO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'PUERTO SANTA ANA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'RINCÓN DE AZARA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'ROCA CHICA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'RUIZ DE MONTOYA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'SALTO ENCANTADO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'SAN ALBERTO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'SAN ANTONIO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'SAN FRANCISCO DE ASÍS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'SAN GOTARDO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'SAN IGNACIO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'SAN JAVIER',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'SAN JOSÉ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'SAN MARTÍN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'SAN MIGUEL',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'SAN PEDRO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'SANTA ANA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'SANTA MARÍA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'SANTA RITA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'SANTIAGO DE LINIERS',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'SANTO PIPÓ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'SAN VICENTE',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'TARUMÁ',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'TOBUNA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'TRES CAPONES',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'VALLE HERMOSO',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'VILLA AKERMAN',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'VILLA BONITA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'VILLA COOPERATIVA',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'VILLA LIBERTAD',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'VILLA PARODI',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'VILLA ROULET',0);
insert into Localidades (fk_Provincia,nombre,baja) Values (4,'VILLA URRUTIA',0);
